update

diff --git a/newroll b/newroll
--- a/newroll
+++ b/newroll
@@ -1,14 +1,14 @@
 #!/bin/bash
-# $Id: newroll,v 1.9 2020/11/23 18:54:45 fulford Exp $
+# $Id: newroll,v 1.11 2021/05/17 13:09:53 fulford Exp fulford $
 # $Source: /src/admin/usr/local/etc/RCS/newroll,v $
-# $Revision: 1.9 $
+# $Revision: 1.11 $
 # Author C W Fulford.
 # Copyright 2016 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0793 572 8612
 ########################################################################
 cmd=`basename $0`
-ver=`echo "$Id: newroll,v 1.9 2020/11/23 18:54:45 fulford Exp $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: newroll,v 1.11 2021/05/17 13:09:53 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
 syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-p] [-v]|-V"
 prep=1
 verbose=1
@@ -18,13 +18,13 @@ while [ $# -gt 0 ] ;do
 		-h) hostid=$2;shift 2;;
 		-p) prep=0;shift;;	
 		-v) verbose=0;shift;;
-		-V) echo "$cmd $Revision: 1.9 $ $Date: 2020/11/23 18:54:45 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.11 $ $Date: 2021/05/17 13:09:53 $"|awk '{print $1,$3,$6}';exit;;  
 	esac
 done
 
 cmd=`basename $0`
 
-mntPt=/media/sdk1
+mntPt=/media/cf
 [ $verbose -eq 0 ] &&  echo $mntPt
 srcDir=$mntPt/DCIM/101EOS5D
 [ $verbose -eq 0 ] &&  echo $srcDir 
@@ -37,8 +37,26 @@ if grep -q "$mntPt" ;then
 	sudo umount $mntPt
 	[ $verbose -eq 0 ] &&  echo "$mntPt unmounted"
 fi
-[ -e /dev/sdk1 ]||{ echo "$cmd: device /dev/sdk1 does not exist." >&2;exit 1 ;} 
-mount /dev/sdk1 ||{ echo "$cmd: on $mntPt failed" >&2;exit 1 ;}
+for dev in sdj1 sdk1 ;do
+  if [ -e /dev/$dev ];then
+	mount /dev/$dev ||{
+		echo "$cmd: on $mntPt failed" >&2; continue
+	}
+	if [ -d $mntPt/DCIM/101EOS5D ] ;then 
+		break
+	else
+		echo "$cmd: $mntPt is not a CF card." >&2;
+		umount $mntPt
+		continue
+	fi
+  else
+	echo "$cmd: device /dev/$dev does not exist." >&2
+  fi 
+done
+if [ ! -d $mntPt/DCIM/101EOS5D ] ;then 
+	echo "$cmd: no images found.">&2
+	exit
+fi
 ##
 
 cd $srcDir ||{ echo "$cmd: cd to $srcDir failed" >&2;exit 1 ;}
@@ -59,10 +77,10 @@ destDir="$destBase/$lastDate-$roll"
 [ $verbose -eq 0 ] && echo $destDir
 mkdir -p $destDir/raw || { echo "$cmd: mkdir $destDir failed" >&2;exit 1 ;}
 cd $srcDir
-[ $verbose -eq 0 ] && { ( n=`cd $destDir/raw;ls)|wc -l`
+mv *.CR2 $destDir/raw/
+[ $verbose -eq 0 ] && {  n=`(cd $destDir/raw;ls|wc -l)`
 			 echo "$cmd: $n CR2 files moved to $destDir/raw"
 }
-mv *.CR2 $destDir/raw/
 
 
 if ls *.MOV >/dev/null 2>&1 ;then
